# Tensor Dimension Information
NODE_FEATURE_DIMENSION = 21
EDGE_FEATURE_DIMENSION = 17
MAX_NUM_PRIMITIVES = 16
MIN_NUM_PRIMITIVES = 7
MAX_NUM_CONSTRAINTS = 208
NUM_PRIMITIVE_TYPES = 5
NUM_CONSTRAINT_TYPES = 9

# Slice objects for indexing into tensors
NODE_BOOL_SLICE = slice(0, 2, 1)
NODE_TYPE_SLICE = slice(2, 7, 1)
NODE_PARM_SLICE = slice(7, 21, 1)

EDGE_SUBA_SLICE = slice(0, 4, 1)
EDGE_SUBB_SLICE = slice(4, 8, 1)
EDGE_TYPE_SLICE = slice(8, 17, 1)

# Training variables
LEARNING_RATE = 1e-4
BATCH_SIZE = 128
NUM_EPOCHS = 1000
TENSORBOARD_RUNS_PATH = "runs"
NUM_TRAJECTORY_VISUALIZATION_IMAGES = 10

# Architecture variables
NODE_HIDDEN_DIM = 512
COND_HIDDEN_DIM = 512
NUM_TRANSFORMER_LAYERS = 32
NUM_ATTENTION_HEADS = 8
MAX_DIFFUSION_TIMESTEP = 2000

# Clamping value for logits in Gaussian-Softmax Diffusion
LOGIT_CLIP = -10

# Loss weights
NODE_BCE_WEIGHT = 1.0
NODE_CE_WEIGHT  = 1.0
NODE_MSE_WEIGHT = 16.0

EDGE_SUBA_WEIGHT = 0.1
EDGE_SUBB_WEIGHT = 0.1
EDGE_TYPE_WEIGHT = 0.1

DATASET_SPLIT_SEED = 4